/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_aliases.h"
#include "LED.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "Timer_1.h"
#include "VDAC8_1.h"
#include "isr_1.h"
#include "ADC_SAR_1.h"
#include "ADC_SAR_aliases.h"
#include "ADC_SAR.h"
#include "VDAC_aliases.h"
#include "VDAC.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

